site:
  title: Flowset
  start_page: flowset:ROOT:intro.adoc
  url: https://docs.flowset.io/
content:
  sources:
  - url: ./
    branches: HEAD
    start_path: content
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./content/supplemental
asciidoc:
  extensions:
    - asciidoctor-kroki
