= Control

**Flowset Control** is a web application that provides administrative functionality for external BPM engines.

+++
<div class="card-block">
  <p>Want to try Flowset Control immediately? Use the public demo stand and explore the interface in minutes.</p>
  <a class="primary-btn" href="https://demo-control.flowset.io/login" target="_blank">Demo stand</a>
</div>
+++

*Key Features*

- **Connection Management:** Easily set up connections to various BPM engines and switch between them as needed.
- **Process Browsing:** Navigate through the processes deployed to the engine.
- **Process Deployment:** Deploy a new version of a business process with a convenient diagram preview.
- **Instance Management:** Manage process instances currently running on the BPM engine.
- **User Task Management:** View user tasks with the ability to reassign them.

[NOTE]
====
Currently, only Camunda 7/Operaton is supported.
====

Flowset Control is built using the open-source https://www.jmix.io[Jmix] framework.
